<a href="https://colab.research.google.com/github/noahcreany/EC_Python101/blob/main/Python101_Strings%2CLists%2CTuples%2CArrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


# Introduction to Python
## Ecology Center Workshop - April 4, 2023



---



###How many people have used Python Before?
> Python is one of the most commonly used programming languages in the world (see below). Python, like R, is an object oriented language that is used in all sorts of applications - from web development, networks, data analytics, and software (Instagram runs on Python). Part of Python's appeal is the simple syntax that can allow you to read and understand what the code is doing - even if it is calling a lot of hidden processes that are happening during compiling. 



<img src='https://github.com/noahcreany/EC_Python101/blob/main/Figures/SearchInterest.png?raw=true'/>


##Tiobe Programming Language Index - March 2023

<table id="top20" class="table table-striped table-top20">
<thead><tr>
<th style="width: 15%">Mar 2023</th>
<th style="width: 15%">Mar 2022</th>
<th title="Difference compared to last year" style="width: 15%">Change</th>
<th style="width: 25%" colspan="2">Programming Language</th>
<th style="width: 15%">Ratings</th>
<th title="Difference compared to last year" style="width: 15%">Change</th>
</tr></thead>
<tbody>
<tr><td>1</td><td>1</td><td></td><td class="td-top20"><img src="https://www.tiobe.com/wp-content/themes/tiobe/tiobe-index/images/Python.png" alt="Python page" style="vertical-align:middle"></td><td>Python</td><td>14.83%</td><td>+0.57%</td></tr><tr><td>2</td><td>2</td><td></td><td class="td-top20"><img src="https://www.tiobe.com/wp-content/themes/tiobe/tiobe-index/images/C.png" alt="C page" style="vertical-align:middle"></td><td>C</td><td>14.73%</td><td>+1.67%</td></tr><tr><td>3</td><td>3</td><td></td><td class="td-top20"><img src="https://www.tiobe.com/wp-content/themes/tiobe/tiobe-index/images/Java.png" alt="Java page" style="vertical-align:middle"></td><td>Java</td><td>13.56%</td><td>+2.37%</td></tr><tr><td>4</td><td>4</td><td></td><td class="td-top20"><img src="https://www.tiobe.com/wp-content/themes/tiobe/tiobe-index/images/C__.png" alt="C++ page" style="vertical-align:middle"></td><td>C++</td><td>13.29%</td><td>+4.64%</td></tr><tr><td>5</td><td>5</td><td></td><td class="td-top20"><img src="https://www.tiobe.com/wp-content/themes/tiobe/tiobe-index/images/C_.png" alt="C# page" style="vertical-align:middle"></td><td>C#</td><td>7.17%</td><td>+1.25%</td></tr><tr><td>6</td><td>6</td><td></td><td class="td-top20"><img src="https://www.tiobe.com/wp-content/themes/tiobe/tiobe-index/images/Visual_Basic.png" alt="Visual Basic page" style="vertical-align:middle"></td><td>Visual Basic</td><td>4.75%</td><td>-1.01%</td></tr><tr><td>7</td><td>7</td><td></td><td class="td-top20"><img src="https://www.tiobe.com/wp-content/themes/tiobe/tiobe-index/images/JavaScript.png" alt="JavaScript page" style="vertical-align:middle"></td><td>JavaScript</td><td>2.17%</td><td>+0.09%</td></tr><tr><td>8</td><td>10</td><td><img src="https://www.tiobe.com/wp-content/themes/tiobe/tpci/images/up.png" alt="change"></td><td class="td-top20"><img src="https://www.tiobe.com/wp-content/themes/tiobe/tiobe-index/images/SQL.png" alt="SQL page" style="vertical-align:middle"></td><td>SQL</td><td>1.95%</td><td>+0.11%</td></tr><tr><td>9</td><td>8</td><td><img src="https://www.tiobe.com/wp-content/themes/tiobe/tpci/images/down.png" alt="change"></td><td class="td-top20"><img src="https://www.tiobe.com/wp-content/themes/tiobe/tiobe-index/images/PHP.png" alt="PHP page" style="vertical-align:middle"></td><td>PHP</td><td>1.61%</td><td>-0.30%</td></tr><tr><td>10</td><td>13</td><td><img src="https://www.tiobe.com/wp-content/themes/tiobe/tpci/images/up.png" alt="change"></td><td class="td-top20"><img src="https://www.tiobe.com/wp-content/themes/tiobe/tiobe-index/images/Go.png" alt="Go page" style="vertical-align:middle"></td><td>Go</td><td>1.24%</td><td>+0.26%</td></tr><tr><td>11</td><td>9</td><td><img src="https://www.tiobe.com/wp-content/themes/tiobe/tpci/images/down.png" alt="change"></td><td class="td-top20"><img src="https://www.tiobe.com/wp-content/themes/tiobe/tiobe-index/images/Assembly_language.png" alt="Assembly language page" style="vertical-align:middle"></td><td>Assembly language</td><td>1.11%</td><td>-0.79%</td></tr><tr><td>12</td><td>15</td><td><img src="https://www.tiobe.com/wp-content/themes/tiobe/tpci/images/up.png" alt="change"></td><td class="td-top20"><img src="https://www.tiobe.com/wp-content/themes/tiobe/tiobe-index/images/MATLAB.png" alt="MATLAB page" style="vertical-align:middle"></td><td>MATLAB</td><td>1.08%</td><td>+0.28%</td></tr><tr><td>13</td><td>12</td><td><img src="https://www.tiobe.com/wp-content/themes/tiobe/tpci/images/down.png" alt="change"></td><td class="td-top20"><img src="https://www.tiobe.com/wp-content/themes/tiobe/tiobe-index/images/Delphi_Object_Pascal.png" alt="Delphi/Object Pascal page" style="vertical-align:middle"></td><td>Delphi/Object Pascal</td><td>1.06%</td><td>-0.06%</td></tr><tr><td>14</td><td>23</td><td><img src="https://www.tiobe.com/wp-content/themes/tiobe/tpci/images/upup.png" alt="change"></td><td class="td-top20"><img src="https://www.tiobe.com/wp-content/themes/tiobe/tiobe-index/images/Scratch.png" alt="Scratch page" style="vertical-align:middle"></td><td>Scratch</td><td>1.00%</td><td>+0.47%</td></tr><tr><td>15</td><td>17</td><td><img src="https://www.tiobe.com/wp-content/themes/tiobe/tpci/images/up.png" alt="change"></td><td class="td-top20"><img src="https://www.tiobe.com/wp-content/themes/tiobe/tiobe-index/images/Classic_Visual_Basic.png" alt="Classic Visual Basic page" style="vertical-align:middle"></td><td>Classic Visual Basic</td><td>0.98%</td><td>+0.38%</td></tr><tr><td>16</td><td>11</td><td><img src="https://www.tiobe.com/wp-content/themes/tiobe/tpci/images/downdown.png" alt="change"></td><td class="td-top20"><img src="https://www.tiobe.com/wp-content/themes/tiobe/tiobe-index/images/R.png" alt="R page" style="vertical-align:middle"></td><td>R</td><td>0.93%</td><td>-0.44%</td></tr><tr><td>17</td><td>30</td><td><img src="https://www.tiobe.com/wp-content/themes/tiobe/tpci/images/upup.png" alt="change"></td><td class="td-top20"><img src="https://www.tiobe.com/wp-content/themes/tiobe/tiobe-index/images/Fortran.png" alt="Fortran page" style="vertical-align:middle"></td><td>Fortran</td><td>0.79%</td><td>+0.40%</td></tr><tr><td>18</td><td>16</td><td><img src="https://www.tiobe.com/wp-content/themes/tiobe/tpci/images/down.png" alt="change"></td><td class="td-top20"><img src="https://www.tiobe.com/wp-content/themes/tiobe/tiobe-index/images/Ruby.png" alt="Ruby page" style="vertical-align:middle"></td><td>Ruby</td><td>0.76%</td><td>+0.10%</td></tr><tr><td>19</td><td>26</td><td><img src="https://www.tiobe.com/wp-content/themes/tiobe/tpci/images/upup.png" alt="change"></td><td class="td-top20"><img src="https://www.tiobe.com/wp-content/themes/tiobe/tiobe-index/images/Rust.png" alt="Rust page" style="vertical-align:middle"></td><td>Rust</td><td>0.73%</td><td>+0.22%</td></tr><tr><td>20</td><td>14</td><td><img src="https://www.tiobe.com/wp-content/themes/tiobe/tpci/images/downdown.png" alt="change"></td><td class="td-top20"><img src="https://www.tiobe.com/wp-content/themes/tiobe/tiobe-index/images/Swift.png" alt="Swift page" style="vertical-align:middle"></td><td>Swift</td><td>0.71%</td><td>-0.20%</td></tr>
</tbody>
</table>

# Python 101

Fortunately for the experienced R users, a lot of syntax is very similar between R and Python. The following are the order of operations (PEMDAS) in Python:

*   Parentheses in Python: ( ) - contain a calculation
*   Exponents in Python: **
*   Divide: /
*   Multiply: * (__NOT__:^)
*   Add: +
*   Subtract: -

Let's run some python code to demonstrate:




In [2]:
# Parentheses
(10-4)+5

11

In [3]:
3+5**2

28

In [4]:
(3+5)**2

64

In [5]:
2/10000

0.0002

In [7]:
2*3

6

##Special Operators


*   Divisor (integer): //
*   Modulus operator: %



In [12]:
11//3

3

In [13]:
11%3

2

A few important differences between R and Python to keep in mind:


1.   The carrot (^) is a bitwise operator for bitmath, not an exponent
2.   Counting in Python begins at 0, so you can get different results between R and Python

```
#R
for (x in 1:10) {
  print(x)
}
output:
[1] 1
[1] 2
[1] 3
[1] 4
[1] 5
[1] 6
[1] 7
[1] 8
[1] 9
[1] 10
```


```
# Python
for _i in range(10):
    print(_i)
output:
0
1
2
3
4
5
6
7
8
9
```






##Python Logical Operators

Many of the logical operators in Python are the same as R


*   Equality: ==
*   Inequality: !=
*   Less than <
*   Less than or equal to: <=



In [14]:
4==3

False

In [15]:
4!=3

True

In [16]:
4<3

False

In [17]:
4>=3

True

## Assigning Variables and Objects

### Because Python is an object-based language we can assign values to variables like in R, but the sytax is slightly different in Python

In [29]:
x = 55
x

55

In [30]:
x+=1
x

56

In [31]:
x = 55
y = x+1
print(x, y)

55 56


####To delete a variable we can use (del var)

In [32]:
y

56

In [33]:
del y

### Variable Naming conventions in Python:
Python has fairly relaxed rules for naming variables, but there are a few conventions that help avoid issues:


* Like R, variable names shouldn't contain spaces:
  * Instead Use: like variable_level or VariableLevel
* Don't use periods! - these are special operators in Pandas that call a column from a dataframe.
  * Variable.level would be read as DataFrame.Column
* Don't use uppercase variable names, sometimes these are excluded from display because they are used in packages and are ''hidden'' variable types.
* Most IDEs will change the color of the font for functions and calls (i.e.: list, var, len, type) so be creative and use different names for things so you don't overwrite these 

## Data Types in Python

In Python, there are technically seven data types, but a few are similar or act the same but will not work if the code is expecting something else.



###Numeric
The most basic are just numeric data types, floats and integers

In [39]:
#create a variable with integer value.
a= 100
print("The type of variable having value", a, " is ", type(a))

The type of variable having value 100  is  <class 'int'>


In [40]:
#create a variable with float value.
b=10.2345
print("The type of variable having value", b, " is ", type(b))

The type of variable having value 10.2345  is  <class 'float'>


There is also a ''complex'' data type that combines integers and strings - honestly I've never seen this used before.

In [41]:
c=100+3j
print("The type of variable having value", c, " is ", type(c))

The type of variable having value (100+3j)  is  <class 'complex'>


###Strings
Next are strings, or text  - these act similar to R. You can use either " or ' when assigning a string. A single quote (') is most common to declare a string.

In [42]:
a = "a string in double quote"
b = 'a string in single quote'
print(a)
print(b)

a string in double quote
a string in single quote


In [43]:
c = a+b
print(c)

a string in double quotea string in single quote


In [46]:
c = a + ' | ' + b
print(c)

a string in double quote | a string in single quote


### Lists
In Python, lists use square brackets and are indexed.

In [127]:
#creating a list with a few integers
mylist = [4,5,6,7,8]
mylist[1]

5

In [128]:
#Get the '2nd' element in the list
mylist[2]

6

In [129]:
#Get the '0th' element in the list
mylist[0]

4

In [130]:
#Get the last element in the list
mylist[-1]

8

In [131]:
#Remove the '0th' element in the list
mylist.remove(mylist[0])
mylist

[5, 6, 7, 8]

In [132]:
#Add a new element to the list - appends to the end of the list
mylist.append(0)
mylist

[5, 6, 7, 8, 0]

In [133]:
#Lists can contain mixed data types
mylist.append('some string')
mylist

[5, 6, 7, 8, 0, 'some string']

###Tuples
Tuples for the most part are like lists, but use regular parentheses. However

In [59]:
#tuple having only integer type of data.
a=(1,2,3,4)
print(a) #prints the whole tuple

(1, 2, 3, 4)


In [60]:
#tuple having multiple type of data.
b=("hello", 1,2,3,"go")
print(b) #prints the whole tuple

('hello', 1, 2, 3, 'go')


In [61]:
#index of tuples are also 0 based.
print(b[4]) #this prints a single element in a tuple, in this case "go"

go


### Dictionaries
Python dictionaries can be used to map "keys" and values". For example, we might have zipcodes and a name for a town like the following:

In [74]:
#We create a dict with curly brackets {key : value}. We can call the key and get the corresponding value.
zipdict = {84321:'Logan',
           84332:'Providence',
           84322:'Utah State University'}


print(f'The zipcode 84332 is assigned to {zipdict[84332]}')

print(f'The zipcode 84321 is assigned to {zipdict[84321]}')


The zipcode 84332 is assigned to Providence
The zipcode 84321 is assigned to Logan


###Boolean Operators
In Python True and False are reserved for boolean operations but can be assigned to variables for use in functions and loops.

In [87]:
Trevor = False
Andy = True
Jordan = True
Elsa = True

for _i in ['Elsa','Jordan','Andy', 'Trevor']:
  print('Will '+_i + ' pass this course? - '+ str(globals()[_i]))

Will Elsa pass this course? - True
Will Jordan pass this course? - True
Will Andy pass this course? - True
Will Trevor pass this course? - False


### Arrays
While lists (and sets) are more or less the same thing in R, Python also uses arrays (from NumPy) for a lot of the same types of vector additions and subtractions. 

Numpy is a very big package in Python, but for demonstration purposes we'll create two arrays and do some calculations

In [113]:
#import numpy - often we abbreviate a package to shorten the call 
import numpy as np #np is the convention for numpy

import numpy as np
a = np.array([1, 2, 3])

<img src = 'https://numpy.org/doc/stable/_images/np_array.png' />



In [114]:
#Create an array with a within a range
np.arange(4)

array([0, 1, 2, 3])

In [116]:
#If you start with this array
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
arr

array([2, 1, 5, 3, 7, 4, 6, 8])

In [118]:
#You can quickly sort the numbers in ascending order with:
arr = np.sort(arr)
arr


array([1, 2, 3, 4, 5, 6, 7, 8])

In [120]:
#If you start with these arrays:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
print(a)
print(b)
#You can concatenate them with np.concatenate().
ab = np.concatenate((a, b))
print(ab)

[1 2 3 4]
[5 6 7 8]
[1 2 3 4 5 6 7 8]


In [125]:
#Or, if you start with these arrays:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])
print('X:\n', x,)
print('Y:\n', y,)
#You can concatenate them with:
xy = np.concatenate((x, y), axis=0)
print('XY:\n',xy)

X:
 [[1 2]
 [3 4]]
Y:
 [[5 6]]
XY:
 [[1 2]
 [3 4]
 [5 6]]
